apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web-profile
  name: web-profile
  namespace: web-profile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-profile
  strategy: {}
  template:
    metadata:
      labels:
        app: web-profile
    spec:
      containers:
      - image: dsamist/mywebsite:v1.2
        imagePullPolicy: Always
        name: web-profile
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        # envFrom:
        # - secretRef:
        #     name: mongo-db-creds