apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-profile
  name: web-profile
  namespace: web-profile
spec:
  ports:
  - port: 3446
    protocol: TCP
    targetPort: 80
  selector:
    app: web-profile
  type: LoadBalancer