apiVersion: v1
kind: Service
metadata:
  labels:
    app: portfolio
  name: portfolio
  namespace: portfolio
spec:
  ports:
  - port: 3446
    protocol: TCP
    targetPort: 80
  selector:
    app: portfolio
  type: NodePort