#this workflow is written to perform CI/CD of my web application to prod

name: Application Deployment

on:
  push:
    branches: [master]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Code Checkout
        uses: actions/checkout@v4


        #I am adding this to include a vulenrability scanner in my CI/CD pipeline using trivy
      - name: Run trivy vulnerability scan in file system mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          trivy-config: trivy.yaml
          # name: Setup QEMU
          # uses: docker/setup-qemu-action@v2

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      
      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/mywebsite:${{ github.sha }}
          secrets:
            CERTIFICATE_CRT=${{secrets.CERTIFICATE_CRT}}
            CERTIFICATE_KEY=${{secrets.CERTIFICATE_KEY}}
            NGINX_CONF=${{secrets.NGINX_CONF}}

      - name: Run trivy vulnerabiliy scanner on my container
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ vars.DOCKER_USERNAME }}/mywebsite:${{ github.sha }}
          format: 'table'
          exit-code: '0'     #this exit code is to ensure that the workflow continues even if there's vulnerability. It can be changed to 1 if you want it to stop
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'


  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions: 
      security-events: write
    steps: 
      - name: code checkout
        uses: actions/checkout@v4

      #install kubectl
      - name: Install Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.26.0'
        id: install
      
      #set the k8s config
      - name: Set the kubernetes config file
        uses: azure/k8s-set-context@v4
        with: 
          method: kubeconfig
          kubeconfig: ${{secrets.KUBECONFIG}}
      
      - name: Display k8s cluster details
        run: |
          kubectl version --short -o yaml
          echo --------------------------
          kubectl get nodes
          kubectl get namespaces


      - name: Replace placeholders token in k8s manifest files
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: '_{_'
          tokenSuffix: '_}_'
          files: '["kubernetes/*.yaml", mywebsite/*.yaml, argo-cd/templates/*.yaml]'
        env:
          NAMESPACE: ${{ vars.NAMESPACE }}
          REPLICAS: ${{ vars.REPLICAS }}
          IMAGE: ${{ vars.DOCKER_USERNAME }}/mywebsite:${{ github.sha }}
          DNS_HOST: ${{ vars.DNS_HOST }}

      - name: scan config files (this can be manifests, helm etc)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scanners: 'config'
          scan-ref: './kubernetes'
          hide-progress: false
          format: 'sarif'
          output: 'trivy-results.sarif'
          exit-code: '0'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
          trivy-config: trivy.yaml 

      - name: Upload result to github security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Update corresponding helm values file for frontend (with retry)
        uses: Wandalen/wretry.action@v1.0.36 # Retries action on fail
        with:
          action: fjogeleit/yaml-update-action@main # Action to retry
          with: |
            valueFile: "mywebsite/values.yaml"
            propertyPath: "image.tag"
            value: ${{ github.sha }}
            branch: master
            message: "Update locate production image tag to ${{ github.sha }}


      
      #deploy k8s object to the cluster
      - name: Deploy k8s object to the cluster
        run: |
          kubectl apply -f kubernetes/deployment.yaml
          kubectl apply -f kubernetes/service.yaml
          kubectl apply -f kubernetes/ingress.yaml

 
        

