#this workflow is written to perform CI/CD of my web application to prod

name: Application Deployment

on:
  push:
    branches: [master]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Login to Docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      
      
      - name: Build Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: dsamist/mywebsite

      - name: Test image
        run: |
          docker run -p 3445:443 -v .:/usr/share/nginx/html mywebsite
          curl --insecure https://localhost:3445

      - name: Push Image to Docker hub
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: dsamist/mywebsite
 
        

